name: Docker Build and Push

concurrency: docker-publish

on:
  schedule:
    - cron: '23 4 */7 * *'
  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths-ignore:
     - README.md
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/backblaze-personal-wine

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [ubuntu22, ubuntu20, ubuntu18]
        include:
          - dockerfile: ubuntu22
            extra_tags: main,latest,ubuntu22
          - dockerfile: ubuntu20
            extra_tags: ubuntu20
          - dockerfile: ubuntu18
            extra_tags: ubuntu18

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ matrix.extra_tags }}
          labels: ${{ steps.meta.outputs.labels }}
